version: '3'

volumes:
  db-data:
    external: false

networks:
  default:
    external:
      name: nat
      
services:
  arangodb:
    image: arangodb:3.2.11
    env_file: .env
    ports:
      - "8529:8529"
    volumes:
      - db-data:/var/lib/arangodb3
